services:
  db:
    image: mariadb:lts
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/usr/bin/mariadb --user=root --password=root --execute "SHOW DATABASES;"',
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      MARIADB_DATABASE: note
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - /mariadb_data:/var/lib/mysql
    ports:
      - 3307:3306

  web:
    environment:
      DATABASE: note
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build: .
    ports:
      - 10000:8080
